### ISSUE TITLE
[GRIN-Node] Choose a different default directory for grin blockchain storage

### ISSUE THREAD

**Issue by MCM-Mike** [Grinnode-live/2020-grin-bug-bash-challenge#1]
**Description**:
Choose a different path for storing the GRIN blockchain. 

**Prerequisites**:
Run a GRIN-Node and make changes the following changes to you grin-server.toml:

**grin-server.toml**
```
#the directory, relative to current, in which the grin blockchain
#is stored
d_root = "/some/other/path"
```

**Expected result:**
After the GRIN-Node is fully synced all related GRIN blockchain files should be in the specified folder. 
Example:

```
lrwxrwxrwx 1 grin grin        40 Apr 22  2020 grin 
-rw-r--r-- 1 grin grin         0 Apr 22  2020 grin.lock
-rw-r--r-- 1 grin grin      7905 Nov 10 10:10 grin-server.toml
drwx------ 4 grin grin      4096 Jan 15  2019 header
drwx------ 2 grin grin      4096 Jan 15  2019 lmdb
drwxr-xr-x 2 grin grin      4096 Apr 22  2020 peer
drwx------ 5 grin grin     4096 Jan 15  2019 txhashset
-rw-r--r-- 1 grin grin 831392297 Dez 11 17:40 txhashset_snapshot_0004fa3384d3.zip
```

**Comment by cekickafa** [comment]
I have tested version grin-5.0.0-beta.3 on windows 10 Home (1903)
I have first run grin to generate server-toml then edited d_root 
d_root = "C:\\GrinTest" 
I run and sync node successfully. Node is synced fully.

Following files are generated in folder  "C:\\GrinTest"
- header (folder)
- Imdb (folder)
- peer (folder)
- txhashset (file)

Following files are in default location C:\Users\username\.grin\main
- chain_data (folder)
- .api_secret (file)
- .foreign_api_secret (file)
- grin-server.log (file)
- grin-server.toml

Some of the folders stated in "Expected results" are missing in specified folder.

**Comment by marekyggdrasil** [comment]
Good work @cekickafa ! Could you copy paste some terminal outputs? I think on Windows you can list content of directory with ‘dir’ command.

also, could you list which folders are missing? Or better provide a terminal output that shows they are missing

**Comment by cekickafa** [comment]
Content of folder in modified path (C:\GrinTest)

```
20.12.2020  13:19    <DIR>          .
20.12.2020  13:19    <DIR>          ..
20.12.2020  11:52                 0 grin.lock
20.12.2020  11:52    <DIR>          header
20.12.2020  11:52    <DIR>          lmdb
20.12.2020  11:52    <DIR>          peer
20.12.2020  13:12    <DIR>          txhashset
               1 File(s)              0 bytes
               6 Dir(s)  121.486.356.480 bytes free
```

These are the missing files/folders:

```
lrwxrwxrwx 1 grin grin        40 Apr 22  2020 grin 
-rw-r--r-- 1 grin grin      7905 Nov 10 10:10 grin-server.toml
-rw-r--r-- 1 grin grin 831392297 Dez 11 17:40 txhashset_snapshot_0004fa3384d3.zip
```

**Comment by marekyggdrasil** [comment]
Now its clear, thanks!
