### ISSUE TITLE
[GRIN-Node] check downloaded checksum hash value 

### ISSUE THREAD

**Issue by MCM-Mike** [Grinnode-live/2020-grin-bug-bash-challenge#23]
**Description**
Download GRIN-Node and compare the downloaded archive checksum,  against the given hash values (sha256).

**Prerequisites**
Download https://github.com/mimblewimble/grin/releases/latest and check if the checksum hash values are correct. 

**Expected result:**
They should match.

**Comment by chandrashekar10** [comment]
**Description**
Download GRIN-Node and compare the downloaded archive checksum, against the given hash values (sha256).


I downloaded the latest version of grin 

```https://github.com/mimblewimble/grin/releases/tag/v4.1.1```

and ran the following command

      Chandrashekars-MacBook-Air:Downloads chandrashekar$ shasum -a 256 grin-v4.1.1-macos.tar.gz 
      cb5f0fd524f8d3116c5ebeca2d8e901fe7dd2be2b9604c425a5b8aa9255236c7  grin-v4.1.1-macos.tar.gz

The Checksum value obtained is 
     
          cb5f0fd524f8d3116c5ebeca2d8e901fe7dd2be2b9604c425a5b8aa9255236c7                        --(1)

This matches with the Checksum value in the  file 

              grin-v4.1.1-macos-sha256sum.txt

which is downloaded and opened using vi editor

<img width="764" alt="Screen Shot 2020-12-20 at 5 42 37 PM" src="https://user-images.githubusercontent.com/24850919/102712998-f8453e00-42ea-11eb-93a8-fb2e9c88b28b.png">


From this we can see 


       SHA256(/Users/runner/work/1/a/grin-v4.1.1-macos.tar.gz)=
       cb5f0fd524f8d3116c5ebeca2d8e901fe7dd2be2b9604c425a5b8aa9255236c7

and the check sum is 

       cb5f0fd524f8d3116c5ebeca2d8e901fe7dd2be2b9604c425a5b8aa9255236c7                     --(2)

Comparing (1) and (2) we can find that the checksums are equal and they match

**Comment by marekyggdrasil** [comment]
Excellent! Thank you!
