### ISSUE TITLE
[GRIN-Wallet] - check downloaded checksum value

### ISSUE THREAD

**Issue by MCM-Mike** [Grinnode-live/2020-grin-bug-bash-challenge#24]
**Description**
Download GRIN-Wallet and compare the downloaded archive checksum, against the given hash values (sha256).

**Prerequisites**
Download https://github.com/mimblewimble/grin-wallet/releases/latest and check if the checksum hash values are correct.

**Expected result:**
They should match.

**Comment by pnnaoned** [comment]
Description
Download GRIN-Wallet and compare the downloaded archive checksum, against the given hash values (sha256).

- I downloaded the latest version of grin-wallet v4.0.0 for Windows from: https://github.com/mimblewimble/grin-wallet/releases/tag/v4.0.0

- the SHA256 HASH displayed on the webiste https://grin.mw/download:
`25108E0BF17766E3D4B83BCFF66371F712FF850F6E0E7F563E8F070575AFE8CA`

- I ran the following command in the Windows PowerShell
```
PS C:\Users\pnnao\Desktop\GRIN_Test_Case> CertUtil -hashfile grin-wallet-v4.0.0-win-x64.zip SHA256
Hachage SHA256 de grin-wallet-v4.0.0-win-x64.zip :
25108e0bf17766e3d4b83bcff66371f712ff850f6e0e7f563e8f070575afe8ca
CertUtil: -hashfile La commande s’est terminée correctement.
PS C:\Users\pnnao\Desktop\GRIN_Test_Case>
```
- The Checksum value obtained is
`25108e0bf17766e3d4b83bcff66371f712ff850f6e0e7f563e8f070575afe8ca`

- This matches with the Checksum value in the file:
`grin-wallet-v4.0.0-win-x64-sha256sum.txt`

**Comment by marekyggdrasil** [comment]
Awesome @pnnaoned thanks!
