### ISSUE TITLE
[GRIN-Wallet][Owner API] testing list of accounts method

### ISSUE THREAD

**Issue by marekyggdrasil** [Grinnode-live/2020-grin-bug-bash-challenge#27]
**Description**
Testing the accounts method from the Owner API

**Prerequisites**

1. GRIN-Node
2. GRIN-Wallet with some accounts setup 

**Test procedure**

1. Run GRIN-Wallet in Owner API listener mode
2. Use [node.js](https://gist.github.com/marekyggdrasil/82716db323b34019bf02237012e0d16f) or [python](https://github.com/grinfans/grin.py/blob/main/wallet_v3.py) to run an encrypted request to [accounts method](https://docs.rs/grin_wallet_api/4.0.0/grin_wallet_api/struct.Owner.html#method.accounts)

**Expected result:**
Request returns a list of accounts stored in the wallet (i.e. mappings between user-specified labels and BIP32 derivation paths. Provide requests and response full payloads as well as wallet and node logs.

**Comment by mojitoo** [comment]
### Prerequisites:

* account 1 : default (Version : grin-wallet 4.0.0)
* account 2 : newaccount (Version : grin-wallet 4.0.0)
* [Wallet_v3.py](https://github.com/grinfans/grin.py/blob/main/wallet_v3.py)

## Step 1 (Runs the wallet's local web API)
  
``` 
grin-wallet owner_api
Password: 
20201220 07:55:46.473 WARN grin_wallet_controller::controller - Starting HTTP Foreign API on Owner server at 127.0.0.1:3420.
20201220 07:55:46.473 WARN grin_wallet_controller::controller - Starting HTTP Owner API server at 127.0.0.1:3420.
20201220 07:55:46.473 WARN grin_wallet_controller::controller - HTTP Owner listener started
``` 
HTTP Owner successfully started.


## Step 2 (Run wallet_v3.py)

Before runnning the script, we need to make sure to edit the configuration.

#change to your grin owner_api sercret file
api_sercet_file = '/Users/path/.grin/main/.owner_api_secret'
#change to you wallet password
wallet_password = 'xxx'

and to add at the end : 
pp.pprint(wallet.accounts())


``` 
pyhton3 wallet_v3.py
[   {'label': 'default', 'path': '0200000000000000000000000000000000'},
    {'label': 'newaccount', 'path': '0200000001000000000000000000000000'}]
```
Request returns a list of accounts stored in the wallet (i.e. mappings between user-specified labels and BIP32 derivation paths. Provide requests and response full payloads as well as wallet and node logs.


## grin-wallet.log
```
20201220 07:55:43.286 INFO grin_util::logger - log4rs is initialized, file level: Info, stdout level: Warn, min. level: Info
20201220 07:55:43.286 INFO grin_wallet - Using wallet configuration file at /Users/workstation/.grin/main/grin-wallet.toml
20201220 07:55:43.287 INFO grin_wallet - This is Grin Wallet version 4.0.0 (git v4.0.0), built for x86_64-apple-darwin by rustc 1.44.1 (c7087fe00 2020-06-17).
20201220 07:55:46.473 WARN grin_wallet_controller::controller - Starting HTTP Foreign API on Owner server at 127.0.0.1:3420.
20201220 07:55:46.473 WARN grin_wallet_controller::controller - Starting HTTP Owner API server at 127.0.0.1:3420.
20201220 07:55:46.473 WARN grin_wallet_controller::controller - HTTP Owner listener started.
```

**Comment by marekyggdrasil** [comment]
Awesome!

**Comment by marekyggdrasil** [comment]
@mojitoo it just occurred to me, if you could also include the JSON payload that you submit to API (just the one that gets encrypted) that would also be very useful.

**Comment by marekyggdrasil** [comment]
@mojitoo I forgot to ask, can you please provide version of wallet that has the owner api listener on?

**Comment by mojitoo** [comment]
- grin-wallet 4.0.0
- Darwin MacBook-Pro-de-Workstation.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
