### ISSUE TITLE
[GRIN-Wallet] test estimate-selection flag

### ISSUE THREAD

**Issue by marekyggdrasil** [Grinnode-live/2020-grin-bug-bash-challenge#45]
**Description**
The objective of this test is to test the [estimate-selection flag](https://docs.grin.mw/getting-started/wallet-handbook/#more-flags)

> -e --estimate-selection if present, performs a "dry-run" of creating the transaction, without actually doing anything and locking the funds. It then lists different output selection strategies (outlined below) and their possible effect on your wallet outputs, if chosen.

**Prerequisites**:
1. Setup two GRIN-Wallets (1) + (2)
2. send funds from wallet (1) to wallet (2) via manual Slatepacks wi `--estimate-selection` flag

The wallet (2) is only required to provide a receiver address.

**Expected result:**
The transaction should **not** be posted. It should be a `dry run`. Expect the funds to **not** get locked. Report you findings. Provide all the outputs.

**Other info:**
For sender wallet include the output of command

```
grin-wallet -V
```

and your environment

```
uname -a
```

**Comment by johndavies24** [comment]
https://gist.github.com/johndavies24/5dc1678096c24fd33210cc893ae083f5

Cant really figure out how to assign this to myself, the issues didnt get cloned when I cloned the repo to try to PR my assignment.  I am sure this has been explained, my bad!

**Comment by johndavies24** [comment]
Also no idea why my markdown syntax isnt working on my gist, but the gist is there 😂

**Comment by marekyggdrasil** [comment]
@johndavies24 thanks for the test and @Paouky thanks for helping keep track of it!

looks like the dry-run performed correctly, thanks for checking that! and as for markdown syntax, the reason why it didn't render is missing `.md` file extension, could you add it there @johndavies24 ?

reviewed and closing!
