### ISSUE TITLE
[GRIN-Node][Owner API 2.0] test the validate_chain API method

### ISSUE THREAD

**Issue by marekyggdrasil** [Grinnode-live/2020-grin-bug-bash-challenge#57]
**Description**
Goal of this issue is to test the [validate_chain API method](https://docs.rs/grin_api/4.1.1/grin_api/trait.OwnerRpc.html#tymethod.validate_chain)

**Prerequisites**

1. GRIN-Node

**Test procedure**

1. Run GRIN-Node in Owner API listener mode
2. Run the [validate_chain API method](https://docs.rs/grin_api/4.1.1/grin_api/trait.OwnerRpc.html#tymethod.validate_chain)

**Expected result:**

Output should match [the example](https://docs.rs/grin_api/4.1.1/grin_api/trait.OwnerRpc.html#json-rpc-example-1). Include all cURL requests and responses.

Include the exact version of your grin-node and also your environment

```
uname -a
```

**Comment by mojitoo** [comment]
* grin v 4.1.1
* Darwin MacBook-Pro-de-Workstation.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

### Step 1 : Run GRIN-Node in Owner API listener mode

``` 
grin server run 
``` 

### Step 2 : Run the validate_chain API method
``` 
workstation@MacBook-Pro-de-Workstation ~ % curl -ugrin:$(cat ~/.grin/main/.api_secret) localhost:3413/v2/owner -d '{"jsonrpc": "2.0", "method": "validate_chain", "params": [], "id": 1}' -w "\n" -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3413 (#0)
* Server auth using Basic with user 'grin'
> POST /v2/owner HTTP/1.1
> Host: localhost:3413
> Authorization: Basic Z3JpbjpNajJuNDFkUVcyN3Y3SXNtNjBiUw==
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 69
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 69 out of 69 bytes
< HTTP/1.1 200 OK
< access-control-allow-origin: *
< access-control-allow-headers: Content-Type, Authorization
< content-type: application/json
< content-length: 67
< date: Fri, 01 Jan 2021 09:49:04 GMT
< 
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "Ok": null
  }
* Connection #0 to host localhost left intact
}
* Closing connection 0
```

**Comment by marekyggdrasil** [comment]
Looks like its working. Thanks for checking!
