### ISSUE TITLE
[GRIN-Wallet] Seed restore test v4.x wallet 

### ISSUE THREAD

**Issue by MCM-Mike** [Grinnode-live/2020-grin-bug-bash-challenge#7]
**Description**:
Restore Grin-Wallet version 5.x from your backup seed.

**Prerequisites**:
Setup your Grin-Wallet version 4.x and save your seed. Then perform a restore test.

**Expected result:**
Your funds should still be available after successful restore test.

Include the output of command

```
grin-wallet -V
```

and your environment

```
uname -a
```

**Comment by marekyggdrasil** [comment]
@ndcroos provided his report in [secret gist](https://gist.github.com/ndcroos/0c36c88638d083986fb85679e1d98f21). Thank you for the good work!
